Repository DPuddinu/agenda-tutorato, pull requests merged in 2024-07, with the labels that each got.

#14 6 create dashboard page
  assets/img/user.svg
  src/homepage.html
  src/styles/common.css
  src/styles/homepage.css
  src/styles/landing.css
Labels: feature

#11 Feature: link register and functions to login form
  assets/img/eye-slash.svg
  assets/img/eye.svg
  assets/img/noto-v1_notebook.svg
  src/index.html
  src/lib/auth.js
  src/lib/common.js
  src/lib/login-user.js
  src/lib/models/user-auth.js
  src/lib/register-user.js
  src/lib/ui.js
  src/login.html
  src/register.html
  src/styles/common.css
  src/styles/ui-form.css
  tests/login-validation.test.js
Labels: feature

#12 create crud logic for appointments
  src/lib/crudAppointment.js
  src/lib/models/appointment.js
  src/styles/common.css
Labels: feature

#15 Feature: add appointment modal
  src/homepage.html
  src/lib/dialog.js
  src/styles/common.css
  src/styles/homepage.css
Labels: ui

#19 9 test appointment crud
  package-lock.json
  package.json
  src/homepage.html
  src/lib/common.js
  src/lib/crud-appointments.js
  src/lib/crudAppointment.js
  src/lib/models/appointment.js
  src/styles/common.css
  tests/crud-appointment.test.js
  tests/login-validation.test.js
  vitest.config.js
Labels: test, feature

#20 16 feature update UI after appointment delete
  src/homepage.html
  src/lib/control-appointments.js
  src/lib/dialog.js
  src/lib/ui.js
Labels: feature

#22 FEATURE: add sort appointments functions and tests
  assets/img/arrow-down.svg
  assets/img/arrow-up.svg
  package-lock.json
  src/homepage.html
  src/lib/sort-appointment.js
  src/lib/ui.js
  src/styles/common.css
  tests/sort-appointments.test.js
Labels: test, feature

#23 Feature: create appointment and update UI
  assets/img/icons/trash-can.svg
  src/homepage.html
  src/lib/auth.js
  src/lib/common.js
  src/lib/control-appointments.js
  src/lib/crud-appointments.js
  src/lib/models/user-auth.js
  src/lib/models/user.js
  src/styles/homepage.css
Labels: feature

#31 fix: bug delete function
  src/lib/control-appointments.js
  src/lib/crud-appointments.js
Labels: bug

#33 FEATURE: add sort table by creation date and category
  src/homepage.html
  src/lib/control-appointments.js
  src/lib/sort-appointment.js
Labels: feature

#32 Function for appointment pagination
  src/homepage.html
  src/lib/control-appointments.js
  src/login.html
  src/styles/homepage.css
Labels: feature, ui

#40 FEATURE: edit appointment
  src/homepage.html
  src/lib/control-appointments.js
  src/lib/crud-appointments.js
  src/lib/dialog.js
  src/styles/homepage.css
Labels: feature

#39 fix: pagination button visibility
  src/homepage.html
  src/lib/control-appointments.js
  src/styles/homepage.css
Labels: bug

#43 BUG: user creation
  src/lib/auth.js
  src/lib/common.js
  src/lib/register-user.js
  src/register.html
Labels: bug

#44 STYLE: aligned input field login page
  src/homepage.html
  src/login.html
  src/register.html
  src/styles/common.css
  src/styles/ui-form.css
Labels: ui

#47 Due Date column
  src/homepage.html
  src/lib/control-appointments.js
  src/styles/common.css
  src/styles/homepage.css
Labels: feature

#48 FEATURE: set completed appointment
  src/lib/common.js
  src/lib/control-appointments.js
  src/styles/common.css
  src/styles/homepage.css
Labels: feature

#50 FEATURE: sort appointments by due date
  src/homepage.html
  src/lib/control-appointments.js
  src/lib/crud-appointments.js
  src/lib/sort-appointment.js
Labels: feature

#51 BUG: preserve order state after appointment delete
  src/lib/common.js
  src/lib/control-appointments.js
Labels: bug

#53 BUG: edit delete appointment
  src/homepage.html
  src/lib/control-appointments.js
  src/lib/crud-appointments.js
Labels: bug
